version: '3'
services:
  web:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app
    links:
      - php
  php:
    build: ./php
    restart: always
    volumes:
      - ./app:/app
